
services:
  app:
    build:
      args:
        user: admin # Change this to your username
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app # Change this to your image name
    container_name: app-laravel # Change this to your container name
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: laravel.test
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend-network

    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`app.it-mak.org`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=9000"

  db:
    image: mysql:8.0
    container_name: mysql-laravel # Change this to your container name
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: nginx-laravel # Change this to your container name
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl  # Mount SSL certificate
    networks:
      - backend-network

    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`app.it-mak.org`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"

networks:
  backend-network:
    external: true

x-bake:
  docker:
    build:
      no-cache: true
      pull: true

# أو تأكد من أنك لا تستخدم:
# DOCKER_BUILDKIT=1
