
services:
  app:
    build:
      args:
        user: admin # Change this to your username
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app # Change this to your image name
    container_name: app-laravel # Change this to your container name
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: laravel.test
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend-network

  db:
    image: mysql:8.0
    container_name: mysql-laravel # Change this to your container name
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: demo_app_db         #${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: password                #${DB_PASSWORD}
      MYSQL_PASSWORD: password               #${DB_PASSWORD}
      MYSQL_USER: admin #${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    ports:
      - "3307:3306"  # اختياري لو أردت الوصول من خارج الحاوية

  nginx:
    image: nginx:alpine
    container_name: nginx-laravel # Change this to your container name
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl  # Mount SSL certificate
    networks:
      - backend-network
    ports:
      - "8081:80"  # تغيير البورت لتجنب تعارض 80
    depends_on:
      - app


networks:
  backend-network:
    external: true

x-bake:
  docker:
    build:
      no-cache: true
      pull: true

# أو تأكد من أنك لا تستخدم:
# DOCKER_BUILDKIT=1
